### ISSUE TITLE
Microsoft Azure Docker deployment

### ISSUE THREAD

**Issue by zergxyz** [making/spring-boot-docker-blank#1]
Hello, thanks for your great example on demo this spring project. Just wondering if we can extend this to make it work for Azure docker deployment? Thanks

**Comment by making** [comment]
You can deploy to Azure easily using Docker Machine.
https://docs.docker.com/machine/

I don't think we need any more ;)

**Comment by making** [comment]
You can create docker-machine environment on Azure as follows:

``` console
docker-machine create -d azure \
--azure-subscription-id=<Your Subscription ID> \
--azure-subscription-cert=<Your cert.pem> \
foo
```

Once, your docker-machine environment is created and execute `eval $(docker-machine env foo)`, you can operate Docker on Azure using `docker` command as local docker.
